services:
    mariadb:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: example
        ports:
            - '3306:3306'
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: example
        ports:
            - '5432:5432'
